version: '3.8'
services:
    php-apache-environment:
      container_name: php-apache
      build:
          context: ./php
          dockerfile: Dockerfile
      depends_on:
          - db
      volumes:
          - .:/var/www/html/
      ports:
          - 8888:80
      environment:
          - "MYSQL_HOST=${MYSQL_HOST}"
          - "MYSQL_DATABASE=${MYSQL_DATABASE}"
          - "MYSQL_USER=${MYSQL_USER}"
          - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
          - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    
    db:
      container_name: db
      image: mysql
      ports:
          - "9906:3306"
      environment:
          - "MYSQL_HOST=${MYSQL_HOST}"
          - "MYSQL_DATABASE=${MYSQL_DATABASE}"
          - "MYSQL_USER=${MYSQL_USER}"
          - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
          - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db
    
    mailhog:
        image: mailhog/mailhog
        logging:
            driver: 'none'  # disable saving logs
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
